#!/bin/bash

# If a bob autocomplete file is available.
if [ -f "$BOBAUTOCMPL" ]; then
	source $BOBAUTOCMPL
fi

# Adopt the prompt to show what the main source for other software is.
if [ -n "$RECIPEFILE" ]; then
	__promptmsg=$RECIPEFILE
elif [ -z "$RECIPEFILE" -a -n "$SOFTWARE_HOMES" ]; then
	__promptmsg="softwarehomes"
else
	__promptmsg="n/a"
fi

export PS1="BoB(\j)($__promptmsg):${__bobBUILDTYPE}@\W \#> "

# Safe aliases. Some people hurt themselves and sometimes others.
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

# "Information" aliases.
alias ?='gmake buildshellinfo verbose_requirements_check=1;'
alias ?ldpath='echo -ne "\nLD_LIBRARY_PATH:\n"; echo $LD_LIBRARY_PATH | tr ":" "\n";'
alias ?path='echo -ne "\nPATH:\n"; echo $PATH | tr ":" "\n";'

# We most often use a "run-script" to start things.
RUNSCRIPT=${RUNSCRIPT:-./run}
if [ -x "$RUNSCRIPT" ]; then
	alias run='$RUNSCRIPT'
else
	echo "BOBSHELL: No run script ($RUNSCRIPT)"
fi
